package com.example.gameonquiz

import android.annotation.SuppressLint
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.example.gameonquiz.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {

    //binding class generated by our viewBinding features
    private lateinit var binding: ActivityMainBinding

    //this creates my screen/activity
    @SuppressLint("SetTextI18n")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        //inflating our layout from the binding class and setting it to our content view
        binding = ActivityMainBinding.inflate(layoutInflater)
        val view = binding.root

        //this defines which xml layout to use as my frontend
        setContentView(view)

        //----add our screens logic (functionality)

        //check username when user clicks on start

        binding.btnStart.setOnClickListener {
            //validate if the username is valid
            val username = binding.etUsername.text //getting the entered text

            if (username != null) {
                if (username.isBlank()) {

                    Log.d("AAA Invalid", "Please fill in your name")

                    // Display a Toast message to inform the user
                    Toast.makeText(this, "Please enter your name.", Toast.LENGTH_SHORT).show()

                } else {

                    //navigate to questions page
                    Log.d("AAA Captured Username", username.toString())

                    //define intent navigation
                    val intent = Intent(this, CategoryActivity::class.java)

                    //pass extra data to the next activity
                    intent.putExtra("username", username.toString()) //passing username
                    intent.putExtra("questionNumber", 1) //make sure to start with question 1

                    startActivity(intent)//start navigating
                    //finish() //removes the activity

                }
            }
        }
    }
}